# configs/proposed.yaml
experiment_name: proposed_g60

model_name: Qwen/Qwen2.5-7B-Instruct

train_path: /home/qa/data2/tmp/project/data/g60_seed42/proposed_train.jsonl
eval_path: /home/qa/data2/tmp/project/data/g60_seed42/eval_val.jsonl
output_dir: /home/qa/data2/tmp/project/ckpt/qwen25_7b/g60_seed42/qwen25_7b_g60_seed42_proposed

max_seq_len: 4096
max_contexts: 5

num_train_epochs: 1.0
learning_rate: 2e-4

per_device_train_batch_size: 1
gradient_accumulation_steps: 16

lora_r: 16
lora_alpha: 32
lora_dropout: 0.05

gradient_checkpointing: true
fp16: true
seed: 42
